spring.application.name=job-service
server.port=8082


spring.datasource.url=jdbc:mysql://localhost:3306/job
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# show the execution time and query count
spring.jpa.properties.hibernate.generate_statistics=true

#register in eureka server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


##you disable the web dependency
#spring.main.web-application-type=none
#openai api key
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.chat.options.model=gpt-5-nano
#
##create randomness or creativity in responses
spring.ai.openai.chat.options.temperature=1.0


##kafka configuration -> consumer side
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=job-group-new
spring.kafka.consumer.auto-offset-reset=earliest

# KEY DESERIALIZER
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer

# VALUE DESERIALIZER
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# TRUST PACKAGE
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.job.service.job_service.EventDrivenUsingKafka.event.JobAppliedEvent

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
