spring.application.name=service-registry
server.port=8761

# Important configs
eureka.client.register-with-eureka=false   
eureka.client.fetch-registry=false
#register-with-eureka=false ? server doesn?t register itself
#fetch-registry=false ? no need to fetch
