version: '3.8'

services:

  service-registry:
    build:
      context: ./service-discovery/service-discovery
    container_name: service-registry
    ports:
      - "8761:8761"

  user-service:
    build:
      context: ./UserServiceMS
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
    environment:
      EUREKA_HOST: service-registry
      MYSQL_HOST: host.docker.internal
      KAFKA_HOST: host.docker.internal
      ZIPKIN_HOST: host.docker.internal